version: '3.8'
services:
  nest-app:
    build:
      context: ./
      dockerfile: ./Dockerfile
    depends_on:
      - mysql-container
      - redis-container
    ports:
      - 3001:3001
    networks:
      - common-network

  mysql-container:
    image: mysql:8.0.26
    volumes:
      - /Users/sirchen/mysql-data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: meeting_room_booking_system
      MYSQL_ROOT_PASSWORD: root
    networks:
      - common-network

  redis-container:
    image: redis:7.0.11
    volumes:
      - /Users/sirchen/redis-data:/data
    networks:
      - common-network

networks:
  common-network:
    driver: bridge
